# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3accdf76cab69388235b1ec11446d2e7166f88be0dad642f4da3eef13b97a54a667452e940c75379fd6539271660d8c886d8ec1122d355e393e100916d5260f0

test:
  secret_key_base: ab678c1e00bea4aaae59e36e40cd074d1cd26622be3130c704ee7d160c06eaf571d4beb0b0f7be99c7ba5f9e17c5a9824f6ae77bab13a266028e33b0e3374357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
